amid: ["em meio a", "no meio de", "entre"]
bliss: ["êxtase", "felicidade"]
at first glance: ["à primeira vista"]
slumber: ["dormir"]
thrash out: ["debater", "discutir"]
plea: ["apelo"]
attire: ["vestuário", "traje"]
blunt: ["brusco"]
newlyweds: ["recém-casados"]
unfolding: ["desdobrando"]
gnawing away: ["corroendo"]
idyll: ["idílio"]
rustling: ["sussurro"]
wealthy: ["rico"]
bystanders: ["transeuntes", "passantes"]
folly: ["insensatez"]
doomed: ["condenado"]
welfare: ["bem-estar"]
assure: ["assegurar"]
low-lying areas: ["áreas de baixa altitude"]
amongst: ["entre"]
gloomy: ["sombrio"]
grimly: ["tristemente", "sombriamente"]
fodder: ["dar forragem aos animais"]
digest: ["digerir"]
first-hand: ["primeira mão", "em primeira mão"]
head off: ["desviar"]
wallowing: ["chafurdando"]
cosset: ["mimado"]
drowned: ["afogado"]
tide: ["maré"]
concede: ["admitir"]
feature (something): ["destacar algo"]
swamped: ["inundado"]
mull: ["ponderar"]
steely: ["feito de aço", "férreo"]
ebullient: ["efervescente"]
